name: Copy and replace

on: workflow_dispatch

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout UAT repo
      uses: actions/checkout@v2
      with:
        repository: blakes24/hflatest-uat
        path: ./uat
        token: ${{ secrets.ACCESS_TOKEN }}

    # Copy site folder to uat
    - name: Copy changes to UAT
      run: |
        git config --global user.email "blakes24@gmail.com"
        git config --global user.name "blakes24"
        rsync -a --delete ./site/ ./uat/site/
        cd uat
        git add .
        if git status | grep -q "Changes to be committed"
        then
          git commit -m "update from dev"
          git push -u origin main
        else
          echo "No changes detected"
        fi
        
        
