name: Push changes to prod

on: workflow_dispatch

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout prod repo
      uses: actions/checkout@v2
      with:
        repository: blakes24/hflatest-prod
        path: ./prod
        token: ${{ secrets.ACCESS_TOKEN }}

    # Copy site folder to prod
    - name: Copy changes to prod
      run: |
        git config --global user.email "blakes24@gmail.com"
        git config --global user.name "blakes24"
        rsync -a --delete ./site/ ./prod
        cd prod
        git add .
        if git status | grep -q "Changes to be committed"
        then
          git commit -m "update from dev"
          git push -u origin main
        else
          echo "No changes detected"
        fi
        
        
